# Generated by Django 4.1.1 on 2022-12-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_category',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
