# Generated by Django 4.1.1 on 2022-12-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_auction_category_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.BooleanField(default=True),
        ),
    ]
